#!/bin/bash
echo -n  -e "\033[1;31mDo you have sudo access? \033[0;32m(y/n): \033[0m"
read -n 1 base
if [ "$base" == "y" ]; then
	echo ""
	echo -e "\033[0;32mStarting installation...\033[0m"
	# Update and install basic stuff
	sudo apt-get update -y
	sudo apt-get install git -y
	sudo apt-get install vim -y
	sudo apt-get install bpython -y
	wget https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh -O ~/.git-prompt.sh
	wget https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -O ~/.git-completion.bash
	sudo apt-get install ack-grep -y
	# Install homesick with gem
	sudo apt-get install ruby-full -y
	sudo gem install homesick
	rm .bash_profile .bashrc
	homesick clone sajnikanth/castle
	homesick link castle
	sudo apt-get install mysql-server -y
	# Install pip and other stuff via pip
	sudo apt-get install python-pip -y
	pip install -U pip
	sudo apt-get install python-dev libmysqlclient-dev -y
	sudo pip install nose selenium nosedbreport mysql-python termcolor flake8
	# Install virtual display
	sudo apt-get install xvfb -y
	sudo apt-get install firefox -y
	# Install chrome and chrome driver
	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
	sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
	sudo apt-get update -y
	sudo apt-get install google-chrome-stable -y
	wget http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
	sudo apt-get install unzip -y
	unzip chromedriver_linux*.zip
	rm chromedriver_linux*.zip
	sudo mv chromedriver /usr/local/bin
	# Install phantomjs
	sudo apt-get install phantomjs -y
	echo ""
	echo -n  -e "\033[1;31mDo you want to install selenium server? \033[0;32m(y/n): \033[0m"
	read -n 1 base
	if [ "$base" == "y" ]; then
		echo ""
		echo -e "\033[0;32mContinuing installation...\033[0m"
		sudo apt-get install openjdk-8-jre-headless -y
		sudo apt-get install apache2 -y
		# download selenium server jar
		mkdir ~/selenium-server && wget -O ~/selenium-server/selenium-server-standalone.jar http://goo.gl/PJUZfa
		# restart apache for good measure
		sudo /etc/init.d/apache2 restart
		# set display
		nohup Xvfb :0 -screen 0 1024x768x24 2>&1 >/dev/null
		export DISPLAY=:0
		nohup java -jar ~/selenium-server/selenium-server-standalone.jar & > selenium.log
		echo ""
		curl "http://localhost:4444/wd/hub/status"
	fi
	echo ""
	echo -e "\033[0;32mAll Done!\033[0m"
else
	echo ""
	echo -e "\033[1;31mGet sudo access first!\033[0m"
fi
